# Generated by Django 5.2.7 on 2025-11-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
